site:
  title: Seedwing
  start_page: docs::index.adoc

content:
  sources:
    - url: ./
      branches: main
      start_path: docs
    - url: https://github.com/seedwing-io/seedwing-policy.git
      branches: main
      start_paths:
        - docs/faq
        - docs/dogma
        - docs/examples
        - swio/docs
        - server/docs

ui: 
  bundle:
    url: https://github.com/seedwing-io/seedwing-antora-ui/releases/download/v0.1.2/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
