site:
  title: Seedwing
  start_page: docs::index.adoc

content:
  sources:
    - url: ./
      branches: main
      start_path: docs
    - url: https://github.com/seedwing-io/seedwing-policy.git
      branches: main
      start_paths:
        - docs/faq
        - docs/dogma
        - docs/examples
        - cli/docs
        - server/docs

ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll
