site:
  title: Seedwing
  start_page: docs::index.adoc

content:
  sources:
    - url: ./
      branches: main
      start_path: docs
    - url: ../seedwing-policy
      branches: main
      start_paths:
        - docs/faq
        - docs/dogma
        - docs/examples
        - cli/docs
        - server/docs

ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
